version: "3.2"
services:
  orsee.docker:
    container_name: orsee
    hostname: orsee.docker.dev
    build:
      context: .
      dockerfile: docker/orsee.dockerfile
    volumes:
      - ./:/var/www
    environment:
      - VIRTUAL_HOST=orsee.docker.dev
      - VIRTUAL_PROTO=https
      - VIRTUAL_PORT=443
    networks:
      - default
      - hts-appteam-local-dev
  mariadb:
    container_name: orsee_mariadb
    image: "mariadb:latest"
    volumes:
      - ./install/:/docker-entrypoint-initdb.d/:ro
    restart: 'always'
    ports:
      - "8018:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: "orsee"
      MYSQL_USER: "orsee"
      MYSQL_PASSWORD: "secret"
networks:
  hts-appteam-local-dev:
    external: true
